export const INCREMENT='INCREMENT'
export const DECREMENT='DECREMENT'
export const MULTIPLY='MULTIPLY'

export const DIVISION='DIVISION'
export const SHOWRESULT='SHOWRESULT'
export const   DELETE_RESULT='DELETE_RESULT'